baseURL = 'https://www.aquilon.dev/'
languageCode = 'en-us'
title = 'Aquilon Security'

[params]
  description = "Cybersecurity Products and Solutions"
  author = "Aquilon Security LLC"

[menu]
  # Menu items can be added here when needed

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# GitHub Pages configuration
[deployment]
  [[deployment.targets]]
    name = "public"
    URL = "public"